export const weatherIcons: { [x: string]: any } = {
    '01n': require('../../assets/images/icons/01n.png'),
    '01d': require('../../assets/images/icons/01d.png'),
    '02n': require('../../assets/images/icons/02n.png'),
    '02d': require('../../assets/images/icons/02d.png'),
    '03d': require('../../assets/images/icons/03d.png'),
    '04d': require('../../assets/images/icons/04d.png'),
    '04n': require('../../assets/images/icons/04n.png'),
    '09d': require('../../assets/images/icons/09d.png'),
    '10d': require('../../assets/images/icons/10d.png'),
    '10n': require('../../assets/images/icons/10n.png'),
    '11n': require('../../assets/images/icons/11n.png'),
    '11d': require('../../assets/images/icons/11d.png'),
    '13d': require('../../assets/images/icons/13d.png'),
    '50d': require('../../assets/images/icons/50d.png'),
};